### PR TITLE
[BOLT-TESTS] Replace cache+ option with ext-tsp

### PR DESCRIPTION
**Pull request by nhuhuan**
ninja check-fb-bolt; grep -rnw . -e "cache+"

no more tests containing "cache+"
"cache+" and "ext-tsp" are aliases

### CODE REVIEW

**Comment by aaupov** [comment]
The change LGTM, but there's a note about GitHub's Pull Requests:
Pull request title and comment are not replicated in the commit message.
Please move the PR title and comment into the commit message, adding "Summary" and "Test Plan" fields.

**Comment by nhuhuan** [comment]
> 

In order to change commit message, I would need to push force, so rewrite history of commit.
Github recommends against it, especially when others still access it using their local repository.
As no new changes other than the commit message itself, I cannot commit and push one more time.
Am I understanding it correctly?

Thank you.

**Comment by nhuhuan** [comment]
I've updated the commit message. The force push will only affect my forked repo as you said.

**Review by aaupov — COMMENTED** [review]
The summary should reflect this repo:
> Replace "cache+" with "ext-tsp" in all FB-internal BOLT tests

->
> Replace "cache+" with "ext-tsp" in all binary BOLT tests

And

> ninja check-fb-bolt;

->
> ninja check-bolt

**Pull request merged**
